### ISSUE TITLE
Transparent background is not available

### ISSUE THREAD

**Issue by crazytyt** [lvgl/lv_lib_gif#15]
I tested it with a GIF animation on NXP RT6010 board and simulator, the background is black.
The actual background color is transparent. 

When I hard code the gif->bgindex = 0xff, the background could be transparency.
It confused me a lot.  could you please verify it at your side?

-Andy

**Comment by kisvegabor** [comment]
Please attach the gif you have tested with.

**Comment by crazytyt** [comment]
![new](https://user-images.githubusercontent.com/680878/105452968-381c8e00-5cba-11eb-8ed7-dce60041c37a.gif)

**Comment by crazytyt** [comment]
I have tried some gif,  no one can be played with transparent background.  Do I miss something?
-Andy

**Comment by crazytyt** [comment]
![image](https://user-images.githubusercontent.com/680878/105455785-0c4fd700-5cbf-11eb-97b9-0fe52e352144.png)

**Comment by crazytyt** [comment]
This is what I got (1 frame)

-Andy

**Comment by kisvegabor** [comment]
Thanks.
I've just fixed it. It works well for me with the "bird gif" you have sent.

**Comment by crazytyt** [comment]
Thanks for your quick fix.
Somehow,  the fix seems not perfect. I have tried another gif and found the background is blink.
Please try this one at your side.
-Andy
![test1](https://user-images.githubusercontent.com/680878/105669199-b88cfa00-5f19-11eb-8b70-c30c65904919.gif)

**Comment by kisvegabor** [comment]
I've checked it and the problem is that on the 6th frame the transparent backgrounds index is 60 while on the other frames it's 63. 

It messes up the LVGL images palette because the gif can change the palette for every frame but lvgl has a "global" palette for the whole image. See the [README of gifdec](https://github.com/lecram/gifdec) for more info.

Normally the rendered image should be stored as RGB888 or ARGB8888 but we store it as 8bit palette to save space but it doesn't work in some cases.

So we can either change to "correct" implementation with (A)RGB image output and accept the 5 times larger memory usage (24 or 32 bit output image + 2 internal 8 bit buffers) or accept the current limitations.

With the "correct method" a 100x100 gif would need 50kB RAM instead of 10 kB.

IMO we should choose the correct implementation instead.

What do you think?

**Comment by crazytyt** [comment]
After I set gif->bgindex = 0xff,  which means the color index is 0xff which doesn't exist in most cases, the background is transparent.  Could you please explain it a little more?
Thanks
-Andy

**Comment by kisvegabor** [comment]
It works because you are lucky. Theoretically, any color of the palette could be changed and the image could become a mess.

**Comment by kisvegabor** [comment]
It should work in the new version.

**Comment by jianjunxia** [comment]
> It works because you are lucky. Theoretically, any color of the palette could be changed and the image could become a mess

I seem to have a similar problem with you on the V7 version
