### ISSUE TITLE
The output shows defects

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lv_lib_gif#19]
Original gif
![03_coffee_200](https://user-images.githubusercontent.com/35251456/106247471-8990c400-624a-11eb-8ca5-ab014315b300.gif)

output gif
![03_coffee_200_out](https://user-images.githubusercontent.com/35251456/106247767-f73cf000-624a-11eb-8d2e-adc7271598d2.gif)

**Comment by guoweilkd** [comment]
I have found the cause of the problem:when gif use Local Color Table and disposal==1,The gif will go wrong。In this case，Subsequent frames will change the color mapping of the previous frame in the gif lib.

**Comment by kisvegabor** [comment]
Hi,

I added some optimizations to the original gif decoder to reduce RAM usage to ~1/6 but it turned out that it causes issues in some cases. See this comment: https://github.com/lvgl/lv_lib_gif/issues/15#issuecomment-768136218

I think the decoder should the reverted to the "original" way of working and we need to accept the large memory usage.
